# Generated by Django 4.2.4 on 2023-08-31 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
