# Generated by Django 4.2.4 on 2023-10-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
