# Generated by Django 4.2.4 on 2023-10-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
