# Generated by Django 4.2.4 on 2023-11-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_remove_post_tags_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='forum.tag'),
        ),
    ]
